### ISSUE TITLE
[BUG] list of dicts in argument_spec.yml are not shown

### ISSUE THREAD

**Issue by marszip** [exaluc/docsible#103]
When you described your values in the argument_spec.yml, list of dicts are not generated and added to the README.md. 

## Environment

- **Docsible Version**: 0.7.24
- **Python Version**: 3.11
- **Operating System**: macOS
- **CLI or Script**: CLI

## To Reproduce

Describe the steps to reproduce the behavior:

When you describe a list of dicts, you see only the main key and not the options.   In example https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#sample-specification there is one of those keys used. 

```
myapp_list_with_dicts:
        type: "list"
        elements: "dict"
        required: false
        default:
          - myapp_food_kind: "meat"
            myapp_food_boiling_required: true
            myapp_food_preparation_time: 60
          - myapp_food_kind: "fruits"
            myapp_food_preparation_time: 5
        description: "A list of dicts with a defined structure and with default a value."
        options:
          myapp_food_kind:
            type: "str"
            choices:
              - "vegetables"
              - "fruits"
              - "grains"
              - "meat"
            required: false
            description: "A string value with a limited list of allowed choices."
```

## Expected Behavior

Show all the separate options. 

## Actual Behavior

Output stops at main key.
