### ISSUE TITLE
Multiple lines for description are not handled

### ISSUE THREAD

**Issue by exaluc** [exaluc/docsible#27]
Hello, Is it possible to have an example for multiline description comment ?

_Originally posted by @Bigouden in https://github.com/exaluc/docsible/issues/22#issuecomment-2289115523_

**Comment by exaluc** [comment]
Only \n is handled for the moment on description

**Comment by Bigouden** [comment]
Wouldn't it be wise to refactor the "title," "required," and "description" sections? For example, by using a variable prefixed with "x-" (similar to how it's done in Docker Compose), which would allow for a more detailed description of each variable.

Adding new properties like `type` and `example` would also be easier.

For example:

```yaml
---
x-docsible:
  var_1:
    title: "Variable 1 Title"
    required: true
    type: str  # str, float, int, bool, list, dict, null, none, ...
    description: |
      Variable description
    example: "v1"
  var_2:
    title: "Variable 2 Title"
    required: true
    type: list  # str, float, int, bool, list, dict, null, none, ...
    description: |
      Variable description
    example:
      - k1: v1
      - k2: v2

var_1: value1
var_2:
  - key1: value1
```

PyYAML is capable of reading this variable, and I think this would allow your tool to handle multiline more easily. Ansible Lint didn’t return any syntax errors related to this variable. However, it’s not usable by Ansible (but that’s the goal).
